import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from '@/components/ui/sonner';
import { LanguageProvider } from '@/lib/language';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{
          background: "radial-gradient(ellipse 120% 80% at 50% 0%, #f0f4ff 0%, #f8fafd 60%, #fdf6ff 100%)",
        }}
      >
        <SessionProvider>
          <LanguageProvider>
            <Toaster richColors position="top-center" />
            {children}
          </LanguageProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
