"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'mn';

const translations = {
  en: {
    home: 'Home',
    courses: 'Courses',
    tests: 'Tests',
    profile: 'Profile',
    admin: 'Admin',
    dashboard: 'Dashboard',
    users: 'Users',
    analytics: 'Analytics',
    settings: 'Settings',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    search: 'Search',
    view: 'View',
    edit: 'Edit',
    delete: 'Delete',
    welcomeBack: 'Welcome back',
    continueLearning: 'Continue Learning',
    viewCourse: 'View Course',
    startTest: 'Start Test',
    takeTest: 'Take Test',
    courseContent: 'Course Content',
    lessons: 'lessons',
    moreLessons: 'more lessons',
    createCourse: 'Create Course',
    createTest: 'Create Test',
    courseManagement: 'Course Management',
    testManagement: 'Test Management',
    userManagement: 'User Management',
    totalUsers: 'Total Users',
    totalCourses: 'Total Courses',
    totalTests: 'Total Tests',
    totalRevenue: 'Total Revenue',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    viewProfile: 'View Profile',
    editUser: 'Edit User',
    sendEmail: 'Send Email',
    deleteUser: 'Delete User',
    courseDeleted: 'Course deleted successfully!',
    testDeleted: 'Test deleted successfully!',
    userDeleted: 'User deleted successfully!',
    failedToDelete: 'Failed to delete',
    editComingSoon: 'Edit functionality coming soon!',
    noCoursesFound: 'No courses found',
    noTestsFound: 'No tests found',
    noUsersFound: 'No users found',
    createFirstCourse: 'Create Your First Course',
    createFirstTest: 'Create Your First Test',
    // Landing page translations
    heroTitle: 'Discover Your Professional Potential',
    heroSubtitle: 'Comprehensive assessments and courses designed for career growth and skill development',
    heroCTA: 'Start Your Journey',
    heroSecondary: 'Explore Assessments',
    howItWorks: 'How It Works',
    step1Title: 'Sign Up & Access',
    step1Desc: 'Create your professional profile and gain access to our assessment platform',
    step2Title: 'Take Assessments',
    step2Desc: 'Complete psychometric tests to evaluate your skills, personality, and career potential',
    step3Title: 'Get Insights',
    step3Desc: 'Receive detailed reports with actionable insights for your professional development',
    step4Title: 'Grow & Learn',
    step4Desc: 'Access personalized courses and continue your professional development journey',
    whyChooseUs: 'Why Choose Our Platform',
    benefit1Title: 'Professional Development',
    benefit1Desc: 'Tailored assessments and courses designed for career advancement',
    benefit2Title: 'Evidence-Based',
    benefit2Desc: 'Scientifically validated tools following international standards',
    benefit3Title: 'Personalized Learning',
    benefit3Desc: 'Adaptive content that grows with your professional journey',
    assessmentTypes: 'Assessment Categories',
    personalityTitle: 'Personality & Motivation',
    personalityDesc: 'Understand your work style, motivations, and interpersonal dynamics',
    aptitudeTitle: 'Cognitive & Aptitude',
    aptitudeDesc: 'Evaluate your logical reasoning, problem-solving, and analytical skills',
    competencyTitle: 'Professional Competencies',
    competencyDesc: 'Assess workplace skills, leadership potential, and career readiness',
    careerTitle: 'Career Guidance',
    careerDesc: 'Get insights into career paths that match your strengths and interests',
    ctaTitle: 'Ready to Unlock Your Potential?',
    ctaSubtitle: 'Join thousands of professionals who have transformed their careers',
    signUp: 'Sign Up Now',
    login: 'Already have an account?',
    loginLink: 'Log in here',
    footerText: 'Empowering professionals through comprehensive assessment and learning solutions',
    // Profile page translations
    testHistory: 'Test History',
    courseHistory: 'Course History',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    privacy: 'Privacy',
    about: 'About',
    age: 'Age',
    gender: 'Gender',
    back: 'Back',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    password: 'Password',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    // Sign up and Login page translations
    createYourAccount: 'Create Your Account',
    joinOurLearning: 'Join our learning community and start your journey',
    unlockYourPotential: 'Unlock your potential with quality education',
    joinThousandsStudents: 'Join 10,000+ students worldwide',
    accessQualityContent: 'Access premium courses and tests',
    enterFullName: 'Enter your full name',
    enterEmailAddress: 'Enter your email address',
    enterPhoneNumber: 'Enter your phone number',
    createSecurePassword: 'Create a secure password',
    secureRegistration: 'Secure Registration',
    secureRegistrationDesc: 'Your information is protected with encryption. We\'ll send a verification email and an SMS code; you can verify using either one.',
    creatingAccount: 'Creating Account',
    createAccount: 'Create Account',
    accountCreatedSuccessfully: 'Account created successfully! Please verify your account.',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Log in here',
    welcomeBack: 'Welcome Back',
    continueYourLearning: 'Continue your learning journey',
    pickUpWhereLeftOff: 'Pick up where you left off',
    accessYourProgress: 'Access your learning progress',
    continueYourJourney: 'Continue your educational journey',
    emailOrPhone: 'Email or Phone Number',
    enterEmailOrPhone: 'Enter email or phone number',
    enterPassword: 'Enter your password',
    forgotPassword: 'Forgot your password',
    signingIn: 'Signing In',
    login: 'Login',
    orContinueWith: 'Or continue with',
    signInWithGoogle: 'Sign in with Google',
    dontHaveAccount: 'Don\'t have an account?',
    signUpHere: 'Sign up here',
    // Test type translations
    allTypes: 'All Types',
    talent: 'Talent',
    aptitude: 'Aptitude',
    clinic: 'Clinic',
    personality: 'Personality',
    // New profile fields
    dateOfBirth: 'Date of Birth',
    education: 'Education',
    family: 'Family Status',
    position: 'Position/Major',
    completeProfiles: 'Complete Profiles',
    incompleteProfiles: 'Incomplete Profiles',
    profileCompletion: 'Profile Completion',
    complete: 'Complete',
    incomplete: 'Incomplete',
    notSet: 'Not set',
    unknown: 'Unknown',
    verified: 'Verified',
    emailVerified: 'Email Verified',
    phoneVerified: 'Phone Verified',
    joined: 'Joined',
    updated: 'Updated',
    // Profile setup translations
    completeYourProfile: 'Complete Your Profile',
    personalizeExperience: "Let's personalize your learning experience",
    whatsYourFirstName: "What's your first name?",
    personalizeWithFirstName: "We'll use this to personalize your experience",
    enterFirstName: 'Enter your first name',
    whatsYourLastName: "What's your last name?",
    personalizeWithLastName: "We'll use this to personalize your experience",
    enterLastName: 'Enter your last name',
    whenWereYouBorn: 'When were you born?',
    ageAppropriateContent: 'This helps us recommend age-appropriate content',
    whatsYourGender: "What's your gender?",
    relevantContent: 'This helps us provide relevant content',
    preferNotToSay: 'Prefer not to say',
    other: 'Other',
    whatsYourEducation: "What's your education level?",
    tailorContent: 'This helps us tailor content to your background',
    selectEducationLevel: 'Select Education Level',
    highSchool: 'High School',
    bachelorsDegree: "Bachelor's Degree",
    mastersDegree: "Master's Degree",
    phd: 'PhD',
    tellUsAboutFamily: 'Tell us about your family',
    understandBackground: 'This helps us understand your background better',
    selectFamilyStatus: 'Select Family Status',
    single: 'Single',
    married: 'Married',
    marriedWithChildren: 'Married with Children',
    divorced: 'Divorced',
    widowed: 'Widowed',
    whatsYourPosition: "What's your position or major?",
    recommendCourses: 'This helps us recommend relevant courses',
    positionPlaceholder: 'e.g., Software Engineer, Computer Science, Teacher',
    completeSetup: 'Complete Setup',
    profileSaved: 'Profile saved successfully! Welcome to your learning journey! 🎉',
    updateDetailsAnytime: 'You can update these details anytime in your profile settings',
    // Admin panel translations
    manageAllUsers: 'Manage all users on the platform',
    searchUsers: 'Search users by name, email, education, position, gender, or family...',
    latestRegistrations: 'Latest user registrations with profile information',
    viewMode: 'View Mode',
    cards: 'Cards',
    table: 'Table',
    recentUsers: 'Recent Users',
    adminUsers: 'Admin Users',
    newThisMonth: 'New This Month',
    completionRate: 'completion rate',
    profileInformation: 'Profile Information',
    contactVerification: 'Contact & Verification',
    accountInfo: 'Account Info',
    basicInformation: 'Basic Information',
    profileDetails: 'Profile Details',
    accountStatus: 'Account Status',
    phone: 'Phone',
    actions: 'Actions',
    noUsersYet: 'No users yet',
    noUsersMatchingSearch: 'No users found matching your search',
    // Education options
    educationHighSchool: 'High School',
    educationBachelors: "Bachelor's Degree",
    educationMasters: "Master's Degree",
    educationPhD: 'PhD',
    educationOther: 'Other',
    // Family status options
    familySingle: 'Single',
    familyMarried: 'Married',
    familyMarriedChildren: 'Married with Children',
    familyDivorced: 'Divorced',
    familyWidowed: 'Widowed',
    familyOther: 'Other',
    // Position examples
    positionStudent: 'Student',
    positionEngineer: 'Software Engineer',
    positionTeacher: 'Teacher',
    positionManager: 'Manager',
    positionOther: 'Other',
    // Dashboard translations
    fromLastMonth: 'from last month',
    commonAdminTasks: 'Common admin tasks and shortcuts',
    recentCourses: 'Recent Courses',
    recentTests: 'Recent Tests',
    questions: 'questions',
    unnamedUser: 'Unnamed User',
    // Verification & SMS
    verifyYourAccount: 'Verify Your Account',
    chooseVerificationMethod: 'Choose your preferred verification method',
    secureAccountAccess: 'Secure account access with verification',
    quickVerification: 'Quick and secure verification process',
    multipleOptions: 'Multiple verification options available',
    verificationOptions: 'Verification Options',
    selectPreferredMethod: 'Select your preferred verification method',
    verifyViaEmail: 'Verify via Email',
    verifyViaSms: 'Verify via SMS',
    provideBothForOptions: 'Tip: Provide both email and phone during signup to unlock both options.',
    smsLimitReached: 'SMS limit reached. Please try again later.',
    noEmailFound: 'No email found. Please sign up again or use SMS verification.',
    noPhoneFound: 'No phone number found. Please sign up again or use email verification.',
    failedToSendEmail: 'Failed to send verification email',
    verificationEmailSent: 'Verification email sent!',
    couldNotSendEmail: 'Could not send verification email',
    failedToSendSms: 'Failed to send SMS code',
    smsCodeSent: 'SMS code sent!',
    couldNotSendSms: 'Could not send SMS code',
    pleaseWaitBeforeResending: 'Please wait before requesting another SMS code',
    tooManySmsAttempts: 'Too many SMS attempts. Please wait before trying again.',
    sending: 'Sending...',
    wait: 'Wait',
    smsVerification: 'SMS Verification',
    enterVerificationCode: 'Enter Verification Code',
    codeSentToPhone: 'Code sent to your phone number',
    quickAndSecure: 'Quick and secure verification',
    expiresIn10Minutes: 'Code expires in 10 minutes',
    sentTo: 'Sent to',
    enterCode: 'Enter code',
    verificationSuccessful: 'Verification successful!',
    invalidOrExpiredCode: 'Invalid or expired code. Please try again.',
    verificationError: 'Verification error occurred',
    didntReceiveCode: "Didn't receive the code?",
    resendCode: 'Resend Code',
    verifying: 'Verifying...',
    verifyCode: 'Verify Code',
    newSmsCodeSent: 'New SMS code sent!',
    backToVerification: 'Back to Verification',
    // Forgot Password & Reset
    forgotPassword: 'Forgot Password?',
    dontWorryReset: 'Don\'t worry! We\'ll help you reset your password',
    quickSmsVerification: 'Quick SMS verification',
    securePasswordReset: 'Secure password reset',
    backToLearningMinutes: 'Back to learning in minutes',
    resetYourPassword: 'Reset Your Password',
    enterPhoneForCode: 'Enter your phone number to receive a verification code',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter your phone number',
    sendResetCode: 'Send Reset Code',
    sending: 'Sending...',
    verificationCodeSent: 'We\'ve sent a verification code to your phone number. Please check your SMS and enter the code to reset your password.',
    didntReceiveSms: 'Didn\'t receive the SMS? Check your phone or try again.',
    codeExpires10Minutes: 'The verification code will expire in 10 minutes for security reasons.',
    enterVerificationCode: 'Enter Verification Code',
    sendAnotherCode: 'Send Another Code',
    wait: 'Wait',
    backToLogin: 'Back to Login',
    // Reset Password
    resetYourPassword: 'Reset Your Password',
    enterNewPasswordBelow: 'Enter your new password below',
    newPassword: 'New Password',
    enterNewPassword: 'Enter your new password',
    confirmNewPassword: 'Confirm New Password',
    confirmNewPasswordPlaceholder: 'Confirm your new password',
    resettingPassword: 'Resetting Password...',
    resetPassword: 'Reset Password',
    rememberPassword: 'Remember your password?',
    logInHere: 'Log in here',
    passwordMustBe6Chars: 'Password must be at least 6 characters.',
    passwordsDontMatch: 'Passwords don\'t match',
    noResetToken: 'No reset token provided',
    passwordResetSuccess: 'Password reset successfully! You are now logged in.',
    passwordResetSuccessLogin: 'Password reset successfully! Please log in with your new password.',
    passwordResetFailed: 'Password reset failed',
    passwordResetError: 'An error occurred during password reset',
    invalidResetLink: 'Invalid reset link. Please request a new password reset.',
    requestNewResetLink: 'Request New Reset Link',
    enterYourNewPassword: 'Enter your new password below',
    enterYourNewPasswordPlaceholder: 'Enter your new password',
    confirmYourNewPassword: 'Confirm your new password',
    loadingResetPasswordPage: 'Loading reset password page...',
    // Additional translations for password reset flow
    codeVerified: 'Code Verified!',
    phoneNumberVerified: 'Your phone number has been verified. You can now reset your password.',
    enterCodeSentTo: 'Enter the 6-digit code sent to',
    quickSmsVerification: 'Quick SMS verification',
    securePasswordReset: 'Secure password reset',
    backToLearningMinutes: 'Back to learning in minutes',
    verificationCodeSent: 'Verification code sent!',
    didntReceiveSms: 'Didn\'t receive the SMS?',
    codeExpires10Minutes: 'The verification code will expire in 10 minutes for security reasons.',
    enterVerificationCode: 'Enter Verification Code',
    sendAnotherCode: 'Send Another Code',
    verificationCodeConfirmed: 'Your verification code has been confirmed. You can now proceed to reset your password.',
    proceedToResetPassword: 'Reset Password',
    didntReceiveCode: 'Didn\'t receive the code?',
    codeExpiresIn10Minutes: 'Code expires in 10 minutes',
    verificationCode: 'Verification Code',
    verificationCodePlaceholder: '000000',
    verifying: 'Verifying...',
    verifyCode: 'Verify Code',
    newVerificationCodeSent: 'New verification code sent!',
    backToForgotPassword: 'Back to Forgot Password',
    securePasswordReset: 'Secure password reset',
    strongPasswordRequirements: 'Strong password requirements',
    instantAccessAfterReset: 'Instant access after reset',
    enterYourNewPassword: 'Enter your new password below',
    enterYourNewPasswordPlaceholder: 'Enter your new password',
    confirmYourNewPassword: 'Confirm your new password',
    confirmYourNewPasswordPlaceholder: 'Confirm your new password',
    resettingPassword: 'Resetting Password...',
    resetPassword: 'Reset Password',
    rememberPassword: 'Remember your password?',
    logInHere: 'Log in here',
    invalidResetLink: 'Invalid reset link. Please request a new password reset.',
    requestNewResetLink: 'Request New Reset Link',
    // SMS Verification page translations
    smsVerification: 'SMS Verification',
    enterVerificationCode: 'Enter Verification Code',
    codeSentToPhone: 'Code sent to your phone number',
    quickAndSecure: 'Quick and secure verification',
    expiresIn10Minutes: 'Code expires in 10 minutes',
    sentTo: 'Sent to',
    enterCode: 'Enter code',
    verificationSuccessful: 'Verification successful!',
    invalidOrExpiredCode: 'Invalid or expired code. Please try again.',
    verificationError: 'Verification error occurred',
    didntReceiveCode: 'Didn\'t receive the code?',
    resendCode: 'Resend Code',
    verifying: 'Verifying...',
    verifyCode: 'Verify Code',
    newSmsCodeSent: 'New SMS code sent!',
    backToVerification: 'Back to Verification',
    pleaseWaitBeforeResending: 'Please wait before requesting another SMS code',
    failedToSendSms: 'Failed to send SMS code',
    couldNotSendSms: 'Could not send SMS code',
    phoneNumberMissing: 'Phone number missing',
    // Additional translations for form validation
    pleaseEnterValidCode: 'Please enter a valid verification code',
    codeMustBe6Digits: 'Code must be 6 digits',
    codeMustBe4Digits: 'Code must be at least 4 digits',
    // Additional translations for success messages
    codeSentSuccessfully: 'Code sent successfully!',
    newCodeSent: 'New code sent!',
    // Additional translations for error messages
    somethingWentWrong: 'Something went wrong. Please try again.',
    networkError: 'Network error. Please check your connection.',
    // Additional translations for form validation
    phoneNumberMustBe8Chars: 'Phone number must be at least 8 characters.',
    countryCodeRequired: 'Country code is required.',
  },
  mn: {
    home: 'Нүүр',
    courses: 'Курсууд',
    tests: 'Тестүүд',
    profile: 'Профайл',
    admin: 'Админ',
    dashboard: 'Хяналтын самбар',
    users: 'Хэрэглэгчид',
    analytics: 'Аналитик',
    settings: 'Тохиргоо',
    loading: 'Уншиж байна...',
    error: 'Алдаа',
    success: 'Амжилттай',
    cancel: 'Цуцлах',
    save: 'Хадгалах',
    close: 'Хаах',
    search: 'Хайх',
    view: 'Харах',
    edit: 'Засах',
    delete: 'Устгах',
    welcomeBack: 'Сайн байна уу',
    continueLearning: 'Үргэлжлүүлэх',
    viewCourse: 'Курс харах',
    startTest: 'Тест эхлэх',
    takeTest: 'Тест өгөх',
    courseContent: 'Курсын агуулга',
    lessons: 'хичээл',
    moreLessons: 'нэмэлт хичээл',
    createCourse: 'Курс үүсгэх',
    createTest: 'Тест үүсгэх',
    courseManagement: 'Курсын удирдлага',
    testManagement: 'Тестийн удирдлага',
    userManagement: 'Хэрэглэгчийн удирдлага',
    totalUsers: 'Нийт хэрэглэгч',
    totalCourses: 'Нийт курс',
    totalTests: 'Нийт тест',
    totalRevenue: 'Нийт орлого',
    recentActivity: 'Сүүлийн үйл ажиллагаа',
    quickActions: 'Шуурхай үйлдлүүд',
    viewProfile: 'Профайл харах',
    editUser: 'Хэрэглэгч засах',
    sendEmail: 'Имэйл илгээх',
    deleteUser: 'Хэрэглэгч устгах',
    courseDeleted: 'Курс амжилттай устгагдлаа!',
    testDeleted: 'Тест амжилттай устгагдлаа!',
    userDeleted: 'Хэрэглэгч амжилттай устгагдлаа!',
    failedToDelete: 'Устгахад алдаа гарлаа',
    editComingSoon: 'Засах функц удахгүй ирэх болно!',
    noCoursesFound: 'Курс олдсонгүй',
    noTestsFound: 'Тест олдсонгүй',
    noUsersFound: 'Хэрэглэгч олдсонгүй',
    createFirstCourse: 'Анхны курсаа үүсгэнэ үү',
    createFirstTest: 'Анхны тестээ үүсгэнэ үү',
    // Landing page translations
    heroTitle: 'Мэргэжлийн боломжоо нээ',
    heroSubtitle: 'Карьерын хөгжил, ур чадварын хөгжүүлэлтэд зориулсан дэлгэрэнгүй үнэлгээ, курс',
    heroCTA: 'Аялаагаа эхлэх',
    heroSecondary: 'Үнэлгээг судлах',
    howItWorks: 'Хэрхэн ажилладаг вэ',
    step1Title: 'Бүртгүүлэх & Хандах',
    step1Desc: 'Мэргэжлийн профайлаа үүсгэж, үнэлгээний платформд хандах',
    step2Title: 'Үнэлгээ өгөх',
    step2Desc: 'Ур чадвар, төрх байдал, карьерын боломжийг үнэлэхийн тулд психометрийн тестүүдийг гүйцээх',
    step3Title: 'Ойлголт авах',
    step3Desc: 'Мэргэжлийн хөгжилд зориулсан үйлдэл хийх боломжтой дэлгэрэнгүй тайлан авах',
    step4Title: 'Хөгжих & Сурах',
    step4Desc: 'Хувийн болгосон курсүүдэд хандаж, мэргэжлийн хөгжлийн аялаагаа үргэлжлүүлэх',
    whyChooseUs: 'Манай платформыг яагаад сонгох вэ',
    benefit1Title: 'Мэргэжлийн хөгжил',
    benefit1Desc: 'Карьерын дээшлэлд зориулсан тохируулсан үнэлгээ, курс',
    benefit2Title: 'Нотолгоонд суурилсан',
    benefit2Desc: 'Олон улсын стандартад нийцсэн шинжлэх ухааны баталгаатай хэрэгслүүд',
    benefit3Title: 'Хувийн болгосон сургалт',
    benefit3Desc: 'Мэргэжлийн аялаатай хамт хөгжиж буй адаптив агуулга',
    assessmentTypes: 'Үнэлгээний төрлүүд',
    personalityTitle: 'Төрх байдал & Урам зориг',
    personalityDesc: 'Ажлын хэв маяг, урам зориг, харилцааны динамикийг ойлгох',
    aptitudeTitle: 'Сэтгэлгээ & Ур чадвар',
    aptitudeDesc: 'Логик сэтгэлгээ, асуулыг шийдвэрлэх, аналитик ур чадвараа үнэлэх',
    competencyTitle: 'Мэргэжлийн ур чадвар',
    competencyDesc: 'Ажлын байрны ур чадвар, удирдлагын боломж, карьерын бэлэн байдлыг үнэлэх',
    careerTitle: 'Карьерын чиглүүлэлт',
    careerDesc: 'Таны хүч чадвар, сонирхолд тохирсон карьерын замуудын талаар ойлголт авах',
    ctaTitle: 'Боломжоо нээхэд бэлэн үү?',
    ctaSubtitle: 'Карьераа өөрчилсөн мянга мянган мэргэжлийн хүмүүстэй нэгдээрэй',
    signUp: 'Одоо бүртгүүлэх',
    login: 'Бүртгэлтэй юу?',
    loginLink: 'Энд нэвтэрнэ үү',
    footerText: 'Дэлгэрэнгүй үнэлгээ, сургалтын шийдлүүдээр мэргэжлийн хүмүүсийг хүчирхэгжүүлэх',
    // Profile page translations
    testHistory: 'Тестийн түүх',
    courseHistory: 'Курсын түүх',
    editProfile: 'Профайл засах',
    changePassword: 'Нууц үг солих',
    privacy: 'Нууцлал',
    about: 'Тухай',
    age: 'Нас',
    gender: 'Хүйс',
    back: 'Буцах',
    name: 'Нэр',
    email: 'Имэйл',
    phoneNumber: 'Утасны дугаар',
    password: 'Нууц үг',
    fullName: 'Бүтэн нэр',
    emailAddress: 'И-мэйл хаяг',
    // Sign up and Login page translations
    createYourAccount: 'Бүртгэл үүсгэх',
    joinOurLearning: 'Манай сургалтын хамт олонд нэгдэж, аялаа эхлээрэй',
    unlockYourPotential: 'Чөлөөт боловсролоор боломжоо нээ',
    joinThousandsStudents: 'Дэлхийн 10,000+ сурагчидтай нэгдээрэй',
    accessQualityContent: 'Премиум курс болон тестүүдэд хандах',
    enterFullName: 'Бүтэн нэрээ оруулна уу',
    enterEmailAddress: 'И-мэйл хаягаа оруулна уу',
    enterPhoneNumber: 'Утасны дугаараа оруулна уу',
    createSecurePassword: 'Аюулгүй нууц үг үүсгэх',
    secureRegistration: 'Аюулгүй бүртгэл',
    secureRegistrationDesc: 'Таны мэдээлэл шифрлэгдсэн. Бид баталгаажуулах и-мэйл болон SMS код илгээнэ; та аль нэгийг ашиглан баталгаажуулж болно.',
    creatingAccount: 'Бүртгэл үүсгэж байна',
    createAccount: 'Бүртгэл үүсгэх',
    accountCreatedSuccessfully: 'Бүртгэл амжилттай үүслээ! Бүртгэлээ баталгаажуулна уу.',
    alreadyHaveAccount: 'Бүртгэлтэй юу?',
    loginHere: 'Энд нэвтэрнэ үү',
    welcomeBack: 'Сайн байна уу',
    continueYourLearning: 'Сургалтын аялаагаа үргэлжлүүл',
    pickUpWhereLeftOff: 'Зогссон газараас үргэлжлүүл',
    accessYourProgress: 'Сургалтын явцад хандах',
    continueYourJourney: 'Боловсролын аялаагаа үргэлжлүүл',
    emailOrPhone: 'И-мэйл эсвэл утасны дугаар',
    enterEmailOrPhone: 'И-мэйл эсвэл утасны дугаараа оруулна уу',
    enterPassword: 'Нууц үгээ оруулна уу',
    forgotPassword: 'Нууц үгээ мартсан',
    signingIn: 'Нэвтэрч байна',
    login: 'Нэвтрэх',
    orContinueWith: 'Эсвэл үргэлжлүүл',
    signInWithGoogle: 'Google-аар нэвтрэх',
    dontHaveAccount: 'Бүртгэлгүй юу?',
    signUpHere: 'Энд бүртгүүлнэ үү',
    selectGender: 'Хүйс сонгох',
    male: 'Эрэгтэй',
    female: 'Эмэгтэй',
    saving: 'Хадгалах...',
    saveChanges: 'Хадгалах',
    currentPassword: 'Одоогийн нууц үг',
    newPassword: 'Шинэ нууц үг',
    confirmNewPassword: 'Шинэ нууц үгээ баталгаажуулах',
    passwordsDoNotMatch: 'Шинэ нууц үг таарахгүй байна.',
    passwordChanged: 'Нууц үг амжилттай солигдлоо!',
    failedToChangePassword: 'Нууц үг солиход алдаа гарлаа.',
    continue: 'Үргэлжлүүлэх',
    noPurchasedCourses: 'Харилцагдсан курс олдсонгүй.',
    startLearning: 'Сургалтын яамыг эхлэх!',
    // Test type translations
    allTypes: 'Бүх төрөл',
    talent: 'Талант',
    aptitude: 'Ур чадвар',
    clinic: 'Клиник',
    personality: 'Төрх байдал',
    // New profile fields
    dateOfBirth: 'Төрсөн огноо',
    education: 'Боловсрол',
    family: 'Гэр бүлийн байдал',
    position: 'Албан тушаал/Мэргэжил',
    completeProfiles: 'Бүрэн профайл',
    incompleteProfiles: 'Бүрэн бус профайл',
    profileCompletion: 'Профайлын бүрэн байдал',
    complete: 'Бүрэн',
    incomplete: 'Бүрэн бус',
    notSet: 'Тохируулаагүй',
    unknown: 'Тодорхойгүй',
    verified: 'Баталгаажсан',
    emailVerified: 'Имэйл баталгаажсан',
    phoneVerified: 'Утас баталгаажсан',
    joined: 'Нэгдсэн',
    updated: 'Шинэчилсэн',
    // Profile setup translations
    completeYourProfile: 'Профайлаа бүрэн бөглөнө үү',
    personalizeExperience: 'Сургалтын туршлагыг хувийн болгоё',
    whatsYourFirstName: 'Таны нэр юу вэ?',
    personalizeWithFirstName: 'Энэ нь таны туршлагыг хувийн болгоход тусална',
    enterFirstName: 'Нэрээ оруулна уу',
    whatsYourLastName: 'Таны овог юу вэ?',
    personalizeWithLastName: 'Энэ нь таны туршлагыг хувийн болгоход тусална',
    enterLastName: 'Овгоо оруулна уу',
    whenWereYouBorn: 'Та хэзээ төрсөн бэ?',
    ageAppropriateContent: 'Энэ нь насны хэмжээнд тохирсон агуулгыг санал болгоход тусална',
    whatsYourGender: 'Таны хүйс юу вэ?',
    relevantContent: 'Энэ нь тохирох агуулгыг санал болгоход тусална',
    preferNotToSay: 'Хэлэхгүй байх',
    other: 'Бусад',
    whatsYourEducation: 'Таны боловсролын түвшин юу вэ?',
    tailorContent: 'Энэ нь таны суурь мэдлэгт тохируулсан агуулгыг санал болгоход тусална',
    selectEducationLevel: 'Боловсролын түвшинг сонгоно уу',
    highSchool: 'Ерөнхий боловсрол',
    bachelorsDegree: 'Бакалаврын зэрэг',
    mastersDegree: 'Магистрын зэрэг',
    phd: 'Докторын зэрэг',
    tellUsAboutFamily: 'Гэр бүлийнхээ тухай хэлнэ үү',
    understandBackground: 'Энэ нь таны суурь мэдлэгийг ойлгоход тусална',
    selectFamilyStatus: 'Гэр бүлийн байдлыг сонгоно уу',
    single: 'Ганц бие',
    married: 'Гэрлэсэн',
    marriedWithChildren: 'Хүүхэдтэй гэрлэсэн',
    divorced: 'Салсан',
    widowed: 'Бэлэвсэн',
    whatsYourPosition: 'Таны албан тушаал эсвэл мэргэжил юу вэ?',
    recommendCourses: 'Энэ нь тохирох курсуудыг санал болгоход тусална',
    positionPlaceholder: 'жишээ нь: Программ хөгжүүлэгч, Компьютерийн ухаан, Багш',
    completeSetup: 'Тохиргоог дуусгах',
    profileSaved: 'Профайл амжилттай хадгалагдлаа! Сургалтын яамыг эхлэхэд тавтай морил! 🎉',
    updateDetailsAnytime: 'Эдгээр мэдээллийг профайлын тохиргоонд хэзээ ч шинэчилж болно',
    // Admin panel translations
    manageAllUsers: 'Платформын бүх хэрэглэгчдийг удирдах',
    searchUsers: 'Нэр, имэйл, боловсрол, албан тушаал, хүйс эсвэл гэр бүлийн байдлаар хайх...',
    latestRegistrations: 'Профайлын мэдээлэлтэй хамгийн сүүлийн хэрэглэгчдийн бүртгэл',
    viewMode: 'Харах горим',
    cards: 'Карт',
    table: 'Хүснэгт',
    recentUsers: 'Сүүлийн хэрэглэгчид',
    adminUsers: 'Админ хэрэглэгчид',
    newThisMonth: 'Энэ сард шинэ',
    completionRate: 'бүрэн байдлын хувь',
    profileInformation: 'Профайлын мэдээлэл',
    contactVerification: 'Холбоо барих & Баталгаажуулалт',
    accountInfo: 'Бүртгэлийн мэдээлэл',
    basicInformation: 'Үндсэн мэдээлэл',
    profileDetails: 'Профайлын дэлгэрэнгүй',
    accountStatus: 'Бүртгэлийн төлөв',
    phone: 'Утас',
    actions: 'Үйлдлүүд',
    noUsersYet: 'Хэрэглэгч одоогоор байхгүй',
    noUsersMatchingSearch: 'Хайлтад тохирох хэрэглэгч олдсонгүй',
    // Education options
    educationHighSchool: 'Ерөнхий боловсрол',
    educationBachelors: 'Бакалаврын зэрэг',
    educationMasters: 'Магистрын зэрэг',
    educationPhD: 'Докторын зэрэг',
    educationOther: 'Бусад',
    // Family status options
    familySingle: 'Ганц бие',
    familyMarried: 'Гэрлэсэн',
    familyMarriedChildren: 'Хүүхэдтэй гэрлэсэн',
    familyDivorced: 'Салсан',
    familyWidowed: 'Бэлэвсэн',
    familyOther: 'Бусад',
    // Position examples
    positionStudent: 'Оюутан',
    positionEngineer: 'Программ хөгжүүлэгч',
    positionTeacher: 'Багш',
    positionManager: 'Менежер',
    positionOther: 'Бусад',
    // Dashboard translations
    fromLastMonth: 'өнгөрсөн сараас',
    commonAdminTasks: 'Нийтлэг админ үйлдлүүд болон товчлуурууд',
    recentCourses: 'Сүүлийн курсууд',
    recentTests: 'Сүүлийн тестүүд',
    questions: 'асуулт',
    unnamedUser: 'Нэргүй хэрэглэгч',
    // Verification & SMS
    verifyYourAccount: 'Бүртгэлээ баталгаажуул',
    chooseVerificationMethod: 'Баталгаажуулах аргаа сонгоно уу',
    secureAccountAccess: 'Баталгаажуулалтаар аюулгүй хандалт',
    quickVerification: 'Хурдан, аюулгүй баталгаажуулалт',
    multipleOptions: 'Олон баталгаажуулах сонголт',
    verificationOptions: 'Баталгаажуулах сонголтууд',
    selectPreferredMethod: 'Хүссэн аргаа сонгоно уу',
    verifyViaEmail: 'И-мэйлээр баталгаажуулах',
    verifyViaSms: 'SMS-ээр баталгаажуулах',
    provideBothForOptions: 'Зөвлөгөө: Бүртгүүлэхдээ и-мэйл болон утасны дугаараа хоёуланг нь оруулснаар хоёуланг нь ашиглах боломжтой болно.',
    smsLimitReached: 'SMS хязгаарт хүрсэн. Дараа дахин оролдоно уу.',
    noEmailFound: 'И-мэйл олдсонгүй. Дахин бүртгүүлнэ үү эсвэл SMS баталгаажуулалтыг ашиглана уу.',
    noPhoneFound: 'Утасны дугаар олдсонгүй. Дахин бүртгүүлнэ үү эсвэл и-мэйл баталгаажуулалтыг ашиглана уу.',
    failedToSendEmail: 'Баталгаажуулах и-мэйл илгээхэд алдаа гарлаа',
    verificationEmailSent: 'Баталгаажуулах и-мэйл илгээгдлээ!',
    couldNotSendEmail: 'Баталгаажуулах и-мэйл илгээх боломжгүй',
    failedToSendSms: 'SMS код илгээхэд алдаа гарлаа',
    smsCodeSent: 'SMS код илгээгдлээ!',
    couldNotSendSms: 'SMS код илгээх боломжгүй',
    pleaseWaitBeforeResending: 'Дахин SMS код хүсэхээс өмнө хүлээнэ үү',
    tooManySmsAttempts: 'Хэт олон SMS оролдлого. Дахин оролдохоос өмнө хүлээнэ үү.',
    sending: 'Илгээж байна...',
    wait: 'Хүлээнэ үү',
    smsVerification: 'SMS Баталгаажуулалт',
    enterVerificationCode: 'Баталгаажуулах кодыг оруулна уу',
    codeSentToPhone: 'Утасны дугаар руу код илгээгдлээ',
    quickAndSecure: 'Хурдан, аюулгүй баталгаажуулалт',
    expiresIn10Minutes: 'Код 10 минутын дараа хүчингүй болно',
    sentTo: 'Илгээсэн',
    enterCode: 'Код оруулна уу',
    verificationSuccessful: 'Баталгаажуулалт амжилттай!',
    invalidOrExpiredCode: 'Буруу эсвэл хүчингүй код. Дахин оролдоно уу.',
    verificationError: 'Баталгаажуулалтын алдаа гарлаа',
    didntReceiveCode: 'Код хүлээгээгүй юу?',
    resendCode: 'Кодыг дахин илгээх',
    verifying: 'Баталгаажуулж байна...',
    verifyCode: 'Кодыг баталгаажуулах',
    newSmsCodeSent: 'Шинэ SMS код илгээгдлээ!',
    backToVerification: 'Баталгаажуулалт руу буцах',
    // Forgot Password & Reset
    forgotPassword: 'Нууц үг мартсан уу?',
    dontWorryReset: 'Бид таны нууц үгээ солихыг түрээслээ!',
    quickSmsVerification: 'Хурдан SMS баталгаажуулалт',
    securePasswordReset: 'Аюулгүй нууц үг солих',
    backToLearningMinutes: 'Хурдан сургалтын аялаагаа үргэлжлүүл',
    resetYourPassword: 'Нууц үгээ солих',
    enterPhoneForCode: 'Нууц үг солихын тулд утасны дугаараа оруулна уу',
    phoneNumber: 'Утасны дугаар',
    enterPhoneNumber: 'Утасны дугаараа оруулна уу',
    sendResetCode: 'Нууц үг солих код илгээх',
    sending: 'Илгээж байна...',
    verificationCodeSent: 'Бид таны утасны дугаар руу баталгаажуулах код илгээсэн. Та SMS-ийг шалгана уу, нууц үгээ солихын тулд кодыг оруулна уу.',
    didntReceiveSms: 'SMS хүлээгээгүй юу? Утасныг шалгана уу эсвэл дахин оролдоно уу.',
    codeExpires10Minutes: 'Баталгаажуулах код 10 минутын дараа хүчингүй болно.',
    enterVerificationCode: 'Баталгаажуулах кодыг оруулна уу',
    sendAnotherCode: 'Кодыг дахин илгээх',
    wait: 'Хүлээнэ үү',
    backToLogin: 'Нэвтрэх рүү буцах',
    // Reset Password
    resetYourPassword: 'Нууц үгээ солих',
    enterNewPasswordBelow: 'Нууц үгээ оруулна уу',
    newPassword: 'Шинэ нууц үг',
    enterNewPassword: 'Шинэ нууц үгээ оруулна уу',
    confirmNewPassword: 'Шинэ нууц үгээ баталгаажуулах',
    confirmNewPasswordPlaceholder: 'Шинэ нууц үгээ баталгаажуулах',
    resettingPassword: 'Нууц үг солих...',
    resetPassword: 'Нууц үг солих',
    rememberPassword: 'Нууц үгээ мартсан уу?',
    logInHere: 'Энд нэвтэрнэ үү',
    passwordMustBe6Chars: 'Нууц үг хамгийн багадаа 6 тэмдэгт байх ёстой.',
    passwordsDontMatch: 'Нууц үг таарахгүй байна.',
    noResetToken: 'Нууц үг солих токен олдсонгүй',
    passwordResetSuccess: 'Нууц үг амжилттай солигдлоо! Та одоо нэвтэрсэн байна.',
    passwordResetSuccessLogin: 'Нууц үг амжилттай солигдлоо! Та одоо нэвтэрсэн байна.',
    passwordResetFailed: 'Нууц үг солих алдаа гарлаа.',
    passwordResetError: 'Нууц үг солих явцад алдаа гарлаа',
    invalidResetLink: 'Нууц үг солих холбоос буруу байна. Та шинэ нууц үг солихыг хүсэлтэй уу.',
    requestNewResetLink: 'Шинэ нууц үг солих холбоос хүсэх',
    enterYourNewPassword: 'Шинэ нууц үгээ оруулна уу',
    enterYourNewPasswordPlaceholder: 'Шинэ нууц үгээ оруулна уу',
    confirmYourNewPassword: 'Шинэ нууц үгээ баталгаажуулах',
    loadingResetPasswordPage: 'Нууц үг солих хуудас уншиж байна...',
    // Additional translations for password reset flow
    codeVerified: 'Код баталгаажлаа!',
    phoneNumberVerified: 'Таны утасны дугаар баталгаажлаа. Та одоо нууц үгээ солих боломжтой.',
    enterCodeSentTo: 'Илгээсэн 6 оронтой кодыг оруулна уу',
    quickSmsVerification: 'Хурдан SMS баталгаажуулалт',
    securePasswordReset: 'Аюулгүй нууц үг солих',
    backToLearningMinutes: 'Хурдан сургалтын аялаагаа үргэлжлүүл',
    verificationCodeSent: 'Баталгаажуулах код илгээгдлээ!',
    didntReceiveSms: 'SMS хүлээгээгүй юу?',
    codeExpires10Minutes: 'Баталгаажуулах код 10 минутын дараа хүчингүй болно.',
    enterVerificationCode: 'Баталгаажуулах кодыг оруулна уу',
    sendAnotherCode: 'Кодыг дахин илгээх',
    verificationCodeConfirmed: 'Таны баталгаажуулах код баталгаажлаа. Та одоо нууц үгээ солих боломжтой.',
    proceedToResetPassword: 'Нууц үг солих',
    didntReceiveCode: 'Код хүлээгээгүй юу?',
    codeExpiresIn10Minutes: 'Код 10 минутын дараа хүчингүй болно',
    verificationCode: 'Баталгаажуулах код',
    verificationCodePlaceholder: '000000',
    verifying: 'Баталгаажуулж байна...',
    verifyCode: 'Кодыг баталгаажуулах',
    newVerificationCodeSent: 'Шинэ баталгаажуулах код илгээгдлээ!',
    backToForgotPassword: 'Нууц үг мартсан руу буцах',
    securePasswordReset: 'Аюулгүй нууц үг солих',
    strongPasswordRequirements: 'Хүчтэй нууц үгийн шаардлага',
    instantAccessAfterReset: 'Солилтын дараа шууд хандалт',
    enterYourNewPassword: 'Шинэ нууц үгээ оруулна уу',
    enterYourNewPasswordPlaceholder: 'Шинэ нууц үгээ оруулна уу',
    confirmYourNewPassword: 'Шинэ нууц үгээ баталгаажуулна уу',
    confirmYourNewPasswordPlaceholder: 'Шинэ нууц үгээ баталгаажуулна уу',
    resettingPassword: 'Нууц үг солих...',
    resetPassword: 'Нууц үг солих',
    rememberPassword: 'Нууц үгээ мартсан уу?',
    logInHere: 'Энд нэвтэрнэ үү',
    invalidResetLink: 'Нууц үг солих холбоос буруу байна. Шинэ нууц үг солихыг хүсэлтэй уу.',
    requestNewResetLink: 'Шинэ нууц үг солих холбоос хүсэх',
    // SMS Verification page translations
    smsVerification: 'SMS Баталгаажуулалт',
    enterVerificationCode: 'Баталгаажуулах кодыг оруулна уу',
    codeSentToPhone: 'Утасны дугаар руу код илгээгдлээ',
    quickAndSecure: 'Хурдан, аюулгүй баталгаажуулалт',
    expiresIn10Minutes: 'Код 10 минутын дараа хүчингүй болно',
    sentTo: 'Илгээсэн',
    enterCode: 'Код оруулна уу',
    verificationSuccessful: 'Баталгаажуулалт амжилттай!',
    invalidOrExpiredCode: 'Буруу эсвэл хүчингүй код. Дахин оролдоно уу.',
    verificationError: 'Баталгаажуулалтын алдаа гарлаа',
    didntReceiveCode: 'Код хүлээгээгүй юу?',
    resendCode: 'Кодыг дахин илгээх',
    verifying: 'Баталгаажуулж байна...',
    verifyCode: 'Кодыг баталгаажуулах',
    newSmsCodeSent: 'Шинэ SMS код илгээгдлээ!',
    backToVerification: 'Баталгаажуулалт руу буцах',
    pleaseWaitBeforeResending: 'Дахин SMS код хүсэхээс өмнө хүлээнэ үү',
    failedToSendSms: 'SMS код илгээхэд алдаа гарлаа',
    couldNotSendSms: 'SMS код илгээх боломжгүй',
    phoneNumberMissing: 'Утасны дугаар олдсонгүй',
    // Additional translations for form validation
    pleaseEnterValidCode: 'Зөв баталгаажуулах кодыг оруулна уу',
    codeMustBe6Digits: 'Код 6 оронтой байх ёстой',
    codeMustBe4Digits: 'Код хамгийн багадаа 4 оронтой байх ёстой',
    // Additional translations for success messages
    codeSentSuccessfully: 'Код амжилттай илгээгдлээ!',
    newCodeSent: 'Шинэ код илгээгдлээ!',
    // Additional translations for error messages
    somethingWentWrong: 'Алдаа гарлаа. Дахин оролдоно уу.',
    networkError: 'Сүлжээний алдаа. Холболтоо шалгана уу.',
    // Additional translations for form validation
    phoneNumberMustBe8Chars: 'Утасны дугаар хамгийн багадаа 8 тэмдэгт байх ёстой.',
    countryCodeRequired: 'Улсын код шаардлагатай.',
  }
};

const LanguageContext = createContext<any>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('preferred-language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'mn')) {
      setLanguage(savedLang);
    }
  }, []);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 