"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'mn';

const translations = {
  en: {
    home: 'Home',
    courses: 'Courses',
    tests: 'Tests',
    profile: 'Profile',
    admin: 'Admin',
    dashboard: 'Dashboard',
    users: 'Users',
    analytics: 'Analytics',
    settings: 'Settings',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    search: 'Search',
    view: 'View',
    edit: 'Edit',
    delete: 'Delete',
    welcomeBack: 'Welcome back',
    continueLearning: 'Continue Learning',
    viewCourse: 'View Course',
    startTest: 'Start Test',
    takeTest: 'Take Test',
    courseContent: 'Course Content',
    lessons: 'lessons',
    moreLessons: 'more lessons',
    createCourse: 'Create Course',
    createTest: 'Create Test',
    courseManagement: 'Course Management',
    testManagement: 'Test Management',
    userManagement: 'User Management',
    totalUsers: 'Total Users',
    totalCourses: 'Total Courses',
    totalTests: 'Total Tests',
    totalRevenue: 'Total Revenue',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    viewProfile: 'View Profile',
    editUser: 'Edit User',
    sendEmail: 'Send Email',
    deleteUser: 'Delete User',
    courseDeleted: 'Course deleted successfully!',
    testDeleted: 'Test deleted successfully!',
    userDeleted: 'User deleted successfully!',
    failedToDelete: 'Failed to delete',
    editComingSoon: 'Edit functionality coming soon!',
    noCoursesFound: 'No courses found',
    noTestsFound: 'No tests found',
    noUsersFound: 'No users found',
    createFirstCourse: 'Create Your First Course',
    createFirstTest: 'Create Your First Test',
    // Profile page translations
    testHistory: 'Test History',
    courseHistory: 'Course History',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    privacy: 'Privacy',
    about: 'About',
    age: 'Age',
    gender: 'Gender',
    back: 'Back',
    name: 'Name',
    email: 'Email',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordsDoNotMatch: 'New passwords do not match.',
    passwordChanged: 'Password changed!',
    failedToChangePassword: 'Failed to change password.',
    continue: 'Continue',
    noPurchasedCourses: 'No purchased courses yet.',
    startLearning: 'Start your learning journey!',
    // Test type translations
    allTypes: 'All Types',
    talent: 'Talent',
    aptitude: 'Aptitude',
    clinic: 'Clinic',
    personality: 'Personality',
    // New profile fields
    dateOfBirth: 'Date of Birth',
    education: 'Education',
    family: 'Family Status',
    position: 'Position/Major',
    completeProfiles: 'Complete Profiles',
    incompleteProfiles: 'Incomplete Profiles',
    profileCompletion: 'Profile Completion',
    complete: 'Complete',
    incomplete: 'Incomplete',
    notSet: 'Not set',
    unknown: 'Unknown',
    verified: 'Verified',
    emailVerified: 'Email Verified',
    phoneVerified: 'Phone Verified',
    joined: 'Joined',
    updated: 'Updated',
    // Profile setup translations
    completeYourProfile: 'Complete Your Profile',
    personalizeExperience: "Let's personalize your learning experience",
    whatsYourName: "What's your name?",
    personalizeWithName: "We'll use this to personalize your experience",
    enterFullName: 'Enter your full name',
    whenWereYouBorn: 'When were you born?',
    ageAppropriateContent: 'This helps us recommend age-appropriate content',
    whatsYourGender: "What's your gender?",
    relevantContent: 'This helps us provide relevant content',
    preferNotToSay: 'Prefer not to say',
    other: 'Other',
    whatsYourEducation: "What's your education level?",
    tailorContent: 'This helps us tailor content to your background',
    selectEducationLevel: 'Select Education Level',
    highSchool: 'High School',
    bachelorsDegree: "Bachelor's Degree",
    mastersDegree: "Master's Degree",
    phd: 'PhD',
    tellUsAboutFamily: 'Tell us about your family',
    understandBackground: 'This helps us understand your background better',
    selectFamilyStatus: 'Select Family Status',
    single: 'Single',
    married: 'Married',
    marriedWithChildren: 'Married with Children',
    divorced: 'Divorced',
    widowed: 'Widowed',
    whatsYourPosition: "What's your position or major?",
    recommendCourses: 'This helps us recommend relevant courses',
    positionPlaceholder: 'e.g., Software Engineer, Computer Science, Teacher',
    completeSetup: 'Complete Setup',
    profileSaved: 'Profile saved successfully! Welcome to your learning journey! 🎉',
    updateDetailsAnytime: 'You can update these details anytime in your profile settings',
    // Admin panel translations
    manageAllUsers: 'Manage all users on the platform',
    searchUsers: 'Search users by name, email, education, position, gender, or family...',
    latestRegistrations: 'Latest user registrations with profile information',
    viewMode: 'View Mode',
    cards: 'Cards',
    table: 'Table',
    recentUsers: 'Recent Users',
    adminUsers: 'Admin Users',
    newThisMonth: 'New This Month',
    completionRate: 'completion rate',
    profileInformation: 'Profile Information',
    contactVerification: 'Contact & Verification',
    accountInfo: 'Account Info',
    basicInformation: 'Basic Information',
    profileDetails: 'Profile Details',
    accountStatus: 'Account Status',
    phone: 'Phone',
    actions: 'Actions',
    noUsersYet: 'No users yet',
    noUsersMatchingSearch: 'No users found matching your search',
    // Education options
    educationHighSchool: 'High School',
    educationBachelors: "Bachelor's Degree",
    educationMasters: "Master's Degree",
    educationPhD: 'PhD',
    educationOther: 'Other',
    // Family status options
    familySingle: 'Single',
    familyMarried: 'Married',
    familyMarriedChildren: 'Married with Children',
    familyDivorced: 'Divorced',
    familyWidowed: 'Widowed',
    familyOther: 'Other',
    // Position examples
    positionStudent: 'Student',
    positionEngineer: 'Software Engineer',
    positionTeacher: 'Teacher',
    positionManager: 'Manager',
    positionOther: 'Other',
    // Dashboard translations
    fromLastMonth: 'from last month',
    commonAdminTasks: 'Common admin tasks and shortcuts',
    recentCourses: 'Recent Courses',
    recentTests: 'Recent Tests',
    questions: 'questions',
    unnamedUser: 'Unnamed User',
  },
  mn: {
    home: 'Нүүр',
    courses: 'Курсууд',
    tests: 'Тестүүд',
    profile: 'Профайл',
    admin: 'Админ',
    dashboard: 'Хяналтын самбар',
    users: 'Хэрэглэгчид',
    analytics: 'Аналитик',
    settings: 'Тохиргоо',
    loading: 'Уншиж байна...',
    error: 'Алдаа',
    success: 'Амжилттай',
    cancel: 'Цуцлах',
    save: 'Хадгалах',
    close: 'Хаах',
    search: 'Хайх',
    view: 'Харах',
    edit: 'Засах',
    delete: 'Устгах',
    welcomeBack: 'Сайн байна уу',
    continueLearning: 'Үргэлжлүүлэх',
    viewCourse: 'Курс харах',
    startTest: 'Тест эхлэх',
    takeTest: 'Тест өгөх',
    courseContent: 'Курсын агуулга',
    lessons: 'хичээл',
    moreLessons: 'нэмэлт хичээл',
    createCourse: 'Курс үүсгэх',
    createTest: 'Тест үүсгэх',
    courseManagement: 'Курсын удирдлага',
    testManagement: 'Тестийн удирдлага',
    userManagement: 'Хэрэглэгчийн удирдлага',
    totalUsers: 'Нийт хэрэглэгч',
    totalCourses: 'Нийт курс',
    totalTests: 'Нийт тест',
    totalRevenue: 'Нийт орлого',
    recentActivity: 'Сүүлийн үйл ажиллагаа',
    quickActions: 'Шуурхай үйлдлүүд',
    viewProfile: 'Профайл харах',
    editUser: 'Хэрэглэгч засах',
    sendEmail: 'Имэйл илгээх',
    deleteUser: 'Хэрэглэгч устгах',
    courseDeleted: 'Курс амжилттай устгагдлаа!',
    testDeleted: 'Тест амжилттай устгагдлаа!',
    userDeleted: 'Хэрэглэгч амжилттай устгагдлаа!',
    failedToDelete: 'Устгахад алдаа гарлаа',
    editComingSoon: 'Засах функц удахгүй ирэх болно!',
    noCoursesFound: 'Курс олдсонгүй',
    noTestsFound: 'Тест олдсонгүй',
    noUsersFound: 'Хэрэглэгч олдсонгүй',
    createFirstCourse: 'Анхны курсаа үүсгэнэ үү',
    createFirstTest: 'Анхны тестээ үүсгэнэ үү',
    // Profile page translations
    testHistory: 'Тестийн түүх',
    courseHistory: 'Курсын түүх',
    editProfile: 'Профайл засах',
    changePassword: 'Нууц үг солих',
    privacy: 'Нууцлал',
    about: 'Тухай',
    age: 'Нас',
    gender: 'Хүйс',
    back: 'Буцах',
    name: 'Нэр',
    email: 'Имэйл',
    selectGender: 'Хүйс сонгох',
    male: 'Эрэгтэй',
    female: 'Эмэгтэй',
    saving: 'Хадгалах...',
    saveChanges: 'Хадгалах',
    currentPassword: 'Одоогийн нууц үг',
    newPassword: 'Шинэ нууц үг',
    confirmNewPassword: 'Шинэ нууц үгээ баталгаажуулах',
    passwordsDoNotMatch: 'Шинэ нууц үг таарахгүй байна.',
    passwordChanged: 'Нууц үг амжилттай солигдлоо!',
    failedToChangePassword: 'Нууц үг солиход алдаа гарлаа.',
    continue: 'Үргэлжлүүлэх',
    noPurchasedCourses: 'Харилцагдсан курс олдсонгүй.',
    startLearning: 'Сургалтын яамыг эхлэх!',
    // Test type translations
    allTypes: 'Бүх төрөл',
    talent: 'Талант',
    aptitude: 'Ур чадвар',
    clinic: 'Клиник',
    personality: 'Төрх байдал',
    // New profile fields
    dateOfBirth: 'Төрсөн огноо',
    education: 'Боловсрол',
    family: 'Гэр бүлийн байдал',
    position: 'Албан тушаал/Мэргэжил',
    completeProfiles: 'Бүрэн профайл',
    incompleteProfiles: 'Бүрэн бус профайл',
    profileCompletion: 'Профайлын бүрэн байдал',
    complete: 'Бүрэн',
    incomplete: 'Бүрэн бус',
    notSet: 'Тохируулаагүй',
    unknown: 'Тодорхойгүй',
    verified: 'Баталгаажсан',
    emailVerified: 'Имэйл баталгаажсан',
    phoneVerified: 'Утас баталгаажсан',
    joined: 'Нэгдсэн',
    updated: 'Шинэчилсэн',
    // Profile setup translations
    completeYourProfile: 'Профайлаа бүрэн бөглөнө үү',
    personalizeExperience: 'Сургалтын туршлагыг хувийн болгоё',
    whatsYourName: 'Таны нэр юу вэ?',
    personalizeWithName: 'Энэ нь таны туршлагыг хувийн болгоход тусална',
    enterFullName: 'Бүтэн нэрээ оруулна уу',
    whenWereYouBorn: 'Та хэзээ төрсөн бэ?',
    ageAppropriateContent: 'Энэ нь насны хэмжээнд тохирсон агуулгыг санал болгоход тусална',
    whatsYourGender: 'Таны хүйс юу вэ?',
    relevantContent: 'Энэ нь тохирох агуулгыг санал болгоход тусална',
    preferNotToSay: 'Хэлэхгүй байх',
    other: 'Бусад',
    whatsYourEducation: 'Таны боловсролын түвшин юу вэ?',
    tailorContent: 'Энэ нь таны суурь мэдлэгт тохируулсан агуулгыг санал болгоход тусална',
    selectEducationLevel: 'Боловсролын түвшинг сонгоно уу',
    highSchool: 'Ерөнхий боловсрол',
    bachelorsDegree: 'Бакалаврын зэрэг',
    mastersDegree: 'Магистрын зэрэг',
    phd: 'Докторын зэрэг',
    tellUsAboutFamily: 'Гэр бүлийнхээ тухай хэлнэ үү',
    understandBackground: 'Энэ нь таны суурь мэдлэгийг ойлгоход тусална',
    selectFamilyStatus: 'Гэр бүлийн байдлыг сонгоно уу',
    single: 'Ганц бие',
    married: 'Гэрлэсэн',
    marriedWithChildren: 'Хүүхэдтэй гэрлэсэн',
    divorced: 'Салсан',
    widowed: 'Бэлэвсэн',
    whatsYourPosition: 'Таны албан тушаал эсвэл мэргэжил юу вэ?',
    recommendCourses: 'Энэ нь тохирох курсуудыг санал болгоход тусална',
    positionPlaceholder: 'жишээ нь: Программ хөгжүүлэгч, Компьютерийн ухаан, Багш',
    completeSetup: 'Тохиргоог дуусгах',
    profileSaved: 'Профайл амжилттай хадгалагдлаа! Сургалтын яамыг эхлэхэд тавтай морил! 🎉',
    updateDetailsAnytime: 'Эдгээр мэдээллийг профайлын тохиргоонд хэзээ ч шинэчилж болно',
    // Admin panel translations
    manageAllUsers: 'Платформын бүх хэрэглэгчдийг удирдах',
    searchUsers: 'Нэр, имэйл, боловсрол, албан тушаал, хүйс эсвэл гэр бүлийн байдлаар хайх...',
    latestRegistrations: 'Профайлын мэдээлэлтэй хамгийн сүүлийн хэрэглэгчдийн бүртгэл',
    viewMode: 'Харах горим',
    cards: 'Карт',
    table: 'Хүснэгт',
    recentUsers: 'Сүүлийн хэрэглэгчид',
    adminUsers: 'Админ хэрэглэгчид',
    newThisMonth: 'Энэ сард шинэ',
    completionRate: 'бүрэн байдлын хувь',
    profileInformation: 'Профайлын мэдээлэл',
    contactVerification: 'Холбоо барих & Баталгаажуулалт',
    accountInfo: 'Бүртгэлийн мэдээлэл',
    basicInformation: 'Үндсэн мэдээлэл',
    profileDetails: 'Профайлын дэлгэрэнгүй',
    accountStatus: 'Бүртгэлийн төлөв',
    phone: 'Утас',
    actions: 'Үйлдлүүд',
    noUsersYet: 'Хэрэглэгч одоогоор байхгүй',
    noUsersMatchingSearch: 'Хайлтад тохирох хэрэглэгч олдсонгүй',
    // Education options
    educationHighSchool: 'Ерөнхий боловсрол',
    educationBachelors: 'Бакалаврын зэрэг',
    educationMasters: 'Магистрын зэрэг',
    educationPhD: 'Докторын зэрэг',
    educationOther: 'Бусад',
    // Family status options
    familySingle: 'Ганц бие',
    familyMarried: 'Гэрлэсэн',
    familyMarriedChildren: 'Хүүхэдтэй гэрлэсэн',
    familyDivorced: 'Салсан',
    familyWidowed: 'Бэлэвсэн',
    familyOther: 'Бусад',
    // Position examples
    positionStudent: 'Оюутан',
    positionEngineer: 'Программ хөгжүүлэгч',
    positionTeacher: 'Багш',
    positionManager: 'Менежер',
    positionOther: 'Бусад',
    // Dashboard translations
    fromLastMonth: 'өнгөрсөн сараас',
    commonAdminTasks: 'Нийтлэг админ үйлдлүүд болон товчлуурууд',
    recentCourses: 'Сүүлийн курсууд',
    recentTests: 'Сүүлийн тестүүд',
    questions: 'асуулт',
    unnamedUser: 'Нэргүй хэрэглэгч',
  }
};

const LanguageContext = createContext<any>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('preferred-language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'mn')) {
      setLanguage(savedLang);
    }
  }, []);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 